name: Auto-Format

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-check:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: llvm-tools-preview, rust-src, rustfmt
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Swoosh! Cleaned the Code
