name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: llvm-tools-preview, rust-src
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

  test:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: llvm-tools-preview, rust-src
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: bootimage
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release
  fmt-check:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: llvm-tools-preview, rust-src
        override: true
    - uses: mbrobbel/rustfmt-check@0.3.0
